services:
  engineering_test:
    image: ghcr.io/etherbeing/engineering_test:${TAG:-latest}
    build:
      context: ../web/app/
      dockerfile: ./Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.engineering_test.rule=Host(`engineering.cd.godjango.dev`)
      - traefik.http.routers.engineering_test.entrypoints=web, websecure
      - traefik.http.services.engineering_test.loadbalancer.server.port=4173
      - traefik.http.services.engineering_test.loadbalancer.passHostHeader=true
      - traefik.docker.network=traefik
    environment:
      - VITE_BACKEND_URL=https://engineering.cd.godjango.dev/
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
